In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

/Users/marlenearredondo/opt/anaconda3/lib/python3.9/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
df = pd.read_csv('cleaned_augmented_2.csv', index_col = 0)
df

,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,...,number_inpatient,number_diagnoses,race_AfricanAmerican,race_Asian,race_Caucasian,race_Hispanic,race_Other,readmitted_<30,readmitted_>30,Diabetes_binary
HighBP,,,,,,,,,,,,,,,,,,,,,
1,1,1,40,1,0,0,0,0,1,0,...,0,9,0,0,1,0,0,0,1,0
0,0,0,25,1,0,0,1,0,0,0,...,5,4,0,0,1,0,0,0,0,0
1,1,1,28,0,0,0,0,1,0,0,...,0,4,0,0,1,0,0,0,0,0
1,0,1,27,0,0,0,1,1,1,0,...,1,9,0,0,1,0,0,0,0,0
1,1,1,24,0,0,0,1,1,1,0,...,0,4,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,1,1,45,0,0,0,0,1,1,0,...,0,5,0,0,1,0,0,0,0,0
1,1,1,18,0,0,0,0,0,0,0,...,0,7,1,0,0,0,0,0,0,1
0,0,1,28,0,0,0,1,1,0,0,...,2,5,0,0,1,0,0,0,1,0
1,0,1,23,0,0,0,0,1,1,0,...,1,9,0,0,1,0,0,0,0,0
1,1,1,25,0,0,1,1,1,0,0,...,0,9,1,0,0,0,0,0,0,1

### PCA

In [3]:
pca = PCA()
pca.fit(df)
cumsum = np.cumsum(pca.explained_variance_ratio_)

In [4]:
d = np.argmax(cumsum >= 0.95) + 1
d

5

In [5]:
pca = PCA(n_components=d)
pca.fit(df)

PCA(n_components=5)

In [6]:
# Get the indices of the top features for each component
top_feature_indices = [component.argsort()[-1::-1][:1] for component in pca.components_]

# Get the feature names for the top features of each component
feature_names = list(df.columns[:-1])  
top_features_names = []

for indices in top_feature_indices:
    top_feature_names = [feature_names[i] for i in indices]
    top_features_names.append(top_feature_names)

In [7]:
top_features_names

[['num_lab_procedures'],
 ['PhysHlth'],
 ['num_medications'],
 ['BMI'],
 ['MentHlth']]

In [8]:
pca = PCA(n_components=d)
pca.fit(df)

PCA(n_components=5)

In [9]:
x_pca = pca.transform(df)

In [10]:
transformed_df = pd.DataFrame(x_pca, columns=['PC{}'.format(i+1) for i in range(d)])

transformed_df.columns = ['{}_{}'.format(top_features_names[i][0], transformed_df.columns[i]) for i in range(len(top_features_names))]

In [11]:
transformed_df

,num_lab_procedures_PC1,PhysHlth_PC2,num_medications_PC3,BMI_PC4,MentHlth_PC5
0,25.076510,20.621222,19.834983,5.323047,8.544266
1,-1.701741,-5.346275,0.462210,-2.412440,-0.493331
2,4.708536,34.899327,-9.053155,-6.016315,7.842525
3,29.842298,-5.972239,-4.806152,0.166638,-0.620421
4,11.941984,-5.181381,-11.052760,-2.345629,1.312165
...,...,...,...,...,...
253675,-18.235291,1.475038,-1.538528,17.145959,-2.093546
253676,9.785051,-6.968723,-4.429917,-8.641597,-1.307823
253677,25.210340,-5.326833,-1.239819,0.689406,-0.273325
253678,28.836723,-5.592002,2.885522,-4.797216,-0.440997
253679,7.851537,-5.800962,-3.039550,-1.957809,-0.717260

In [12]:
transformed_df.to_csv('pca_transformed_data.csv')